---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  ports:
  - name: mosquitto
    port: 1883
  selector:
    app: mosquitto
    tier: frontend
  type: ClusterIP
