---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: maestro-api
  name: maestro-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maestro-api
  template:
    metadata:
      labels:
        app: maestro-api
    spec:
      containers:
      - name: maestro-api
        image: quay.io/morvencao/maestro-api:latest
        imagePullPolicy: Always
        args:
        - "/maestro"
        ports:
        - name: maestro-grpc
          containerPort: 8080
          protocol: TCP
        - name: maestro-api
          containerPort: 8090
          protocol: TCP
        envFrom:
        - secretRef:
            name: maestro-config
