---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: maestro-api
  name: maestro-api
spec:
  ports:
  - name: maestro-api
    port: 8090
    nodePort: 31330
  selector:
    app: maestro-api
  type: NodePort
